# Generated by Django 3.1.4 on 2021-01-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210118_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='slide_image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
