# Generated by Django 3.1.4 on 2021-01-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210118_1652'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='color',
            table='colors',
        ),
        migrations.AlterModelTable(
            name='feature',
            table='features',
        ),
        migrations.AlterModelTable(
            name='inspiration',
            table='inspirations',
        ),
        migrations.AlterModelTable(
            name='main',
            table='mains',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='productimages',
        ),
        migrations.AlterModelTable(
            name='productservice',
            table='productservices',
        ),
        migrations.AlterModelTable(
            name='productspecification',
            table='productspecifications',
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
        migrations.AlterModelTable(
            name='specification',
            table='specifications',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategories',
        ),
    ]
