# Generated by Django 3.1.4 on 2021-01-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210119_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspiration',
            name='slide_image_url',
        ),
        migrations.RemoveField(
            model_name='inspiration',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='image_url',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='subtitle',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='description',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='title',
            field=models.JSONField(),
        ),
    ]
